import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronRight, Clock3, Instagram, MapPin, Menu, MessageCircle, Minus, Phone, Plus, ShoppingBag, Trash2, X } from "lucide-react";
import { Button } from "@/components/Button";
import { categoryLabels, favorites, menuItems, restaurant, type Category, type Locale, type MenuItem } from "@/data/restaurant";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "ODA Burger Bahrain — Every Bite, a Legend" },
    { name: "description", content: "Explore ODA Burger's bold burgers, crispy sides and kids meals in Bahrain. Order directly on WhatsApp." },
    { property: "og:title", content: "ODA Burger Bahrain — Every Bite, a Legend" },
    { property: "og:description", content: "Bold burgers, fresh ingredients and legendary flavor in Bahrain." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }), component: Index,
});

type CartItem = { item: MenuItem; option: "sandwich" | "meal" | "single"; price: number; quantity: number };
const t = {
  en: { home: "Home", menu: "Menu", about: "About", contact: "Contact", order: "Order Now", viewMenu: "View Menu", heroKicker: "Born in Bahrain · Built with flavor", heroCopy: "Bold burgers. Fresh ingredients. Legendary flavor.", favorites: "Customer Favorites", favoritesCopy: "The legends our customers come back for.", fullMenu: "The Full Lineup", menuCopy: "Pick your category. Choose your build. Make it legendary.", all: "All", from: "From", quickOrder: "Order", sandwich: "Sandwich", meal: "Meal", add: "Add to Order", story: "Our Story", aboutTitle: "Every Bite, a Legend.", aboutCopy: "At ODA Burger, we believe every burger should be more than just a meal. From bold flavors to carefully selected ingredients, every bite is made to leave a legend behind.", social: "Fresh from ODA", follow: "Follow Us on Instagram", find: "Find ODA", visit: "Visit Us", mapCopy: "Open our current location in Google Maps for directions.", directions: "Get Directions", hours: "Opening Hours", hoursPending: "Hours will be announced soon.", call: "Call", whatsapp: "WhatsApp", cart: "Your Order", empty: "Your order is waiting for its first legend.", subtotal: "Subtotal", checkout: "Checkout on WhatsApp", close: "Close", remove: "Remove", added: "Added to your order", currency: "BHD", nav: "Open navigation", basket: "Open order", footer: "Bold flavor, made to be remembered." },
  ar: { home: "الرئيسية", menu: "القائمة", about: "عن أودا", contact: "تواصل معنا", order: "اطلب الآن", viewMenu: "شاهد القائمة", heroKicker: "وُلد في البحرين · صُنع بالنكهة", heroCopy: "برغر جريء. مكونات طازجة. نكهة أسطورية.", favorites: "اختيارات الزبائن", favoritesCopy: "النكهات الأسطورية التي يعود إليها زبائننا.", fullMenu: "قائمة أودا", menuCopy: "اختر الفئة، حدد وجبتك، واستمتع بالنكهة.", all: "الكل", from: "يبدأ من", quickOrder: "اطلب", sandwich: "ساندويتش", meal: "وجبة", add: "أضف إلى الطلب", story: "قصتنا", aboutTitle: "كل قضمة، أسطورة.", aboutCopy: "في أودا برقر، نؤمن أن كل برغر يجب أن يكون أكثر من مجرد وجبة. من النكهات الجريئة إلى المكونات المختارة بعناية، كل قضمة مصنوعة لتترك أسطورة خلفها.", social: "جديد أودا", follow: "تابعنا على إنستغرام", find: "اعثر على أودا", visit: "زورونا", mapCopy: "افتح موقعنا الحالي في خرائط Google للحصول على الاتجاهات.", directions: "الاتجاهات", hours: "ساعات العمل", hoursPending: "سيتم الإعلان عن ساعات العمل قريباً.", call: "اتصل", whatsapp: "واتساب", cart: "طلبك", empty: "طلبك ينتظر أول نكهة أسطورية.", subtotal: "المجموع", checkout: "إكمال الطلب عبر واتساب", close: "إغلاق", remove: "حذف", added: "تمت الإضافة إلى طلبك", currency: "د.ب", nav: "فتح القائمة", basket: "فتح الطلب", footer: "نكهة جريئة، صنعت لتُذكر." },
};

function Index() {
  const [locale, setLocale] = useState<Locale>("en");
  const [category, setCategory] = useState<Category | "all">("all");
  const [selected, setSelected] = useState<MenuItem | null>(null);
  const [option, setOption] = useState<"sandwich" | "meal" | "single">("single");
  const [cart, setCart] = useState<CartItem[]>([]);
  const [cartOpen, setCartOpen] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const copy = t[locale];
  const isAr = locale === "ar";
  const filtered = category === "all" ? menuItems : menuItems.filter((i) => i.category === category);
  const favoriteItems = favorites.map((id) => menuItems.find((i) => i.id === id)).filter((i): i is MenuItem => Boolean(i));
  const count = cart.reduce((sum, line) => sum + line.quantity, 0);
  const total = cart.reduce((sum, line) => sum + line.price * line.quantity, 0);
  const selectedPrice = selected ? option === "meal" ? selected.meal ?? selected.price ?? 0 : option === "sandwich" ? selected.sandwich ?? selected.price ?? 0 : selected.price ?? 0 : 0;

  useEffect(() => { document.documentElement.dir = isAr ? "rtl" : "ltr"; document.documentElement.lang = locale; }, [isAr, locale]);
  useEffect(() => { if (!selected && !cartOpen && !mobileOpen) return; const close = (e: KeyboardEvent) => { if (e.key === "Escape") { setSelected(null); setCartOpen(false); setMobileOpen(false); } }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [selected, cartOpen, mobileOpen]);

  const openItem = (item: MenuItem) => { setSelected(item); setOption(item.sandwich ? "sandwich" : "single"); };
  const addToCart = (item: MenuItem, choice: CartItem["option"] = item.sandwich ? "sandwich" : "single") => {
    const price = choice === "meal" ? item.meal ?? 0 : choice === "sandwich" ? item.sandwich ?? 0 : item.price ?? 0;
    setCart((current) => { const index = current.findIndex((line) => line.item.id === item.id && line.option === choice); if (index < 0) return [...current, { item, option: choice, price, quantity: 1 }]; return current.map((line, i) => i === index ? { ...line, quantity: line.quantity + 1 } : line); });
    setSelected(null); setCartOpen(true);
  };
  const updateQty = (index: number, delta: number) => setCart((current) => current.flatMap((line, i) => i !== index ? [line] : line.quantity + delta > 0 ? [{ ...line, quantity: line.quantity + delta }] : []));
  const whatsappUrl = useMemo(() => {
    const lines = cart.map((line) => `${line.quantity}x ${line.item.name}${line.option !== "single" ? ` - ${line.option === "meal" ? "Meal" : "Sandwich"}` : ""}`);
    const message = `Hello ODA Burger,\nI would like to place the following order:\n\n${lines.join("\n")}\n\nTotal: ${total.toFixed(1)} BHD`;
    return `https://wa.me/${restaurant.whatsapp}?text=${encodeURIComponent(message)}`;
  }, [cart, total]);
  const heroItem = menuItems.find((item) => item.id === "2jz");
  const aboutItem = menuItems.find((item) => item.id === "1jz");
  const socialItems = ["2jz", "rb26", "single-fries", "kids-meal"].map((id) => menuItems.find((item) => item.id === id)).filter((item): item is MenuItem => Boolean(item));
  const categories: Array<Category | "all"> = ["all", "beef", "chicken", "sides", "drinks", "kids"];
  if (!heroItem || !aboutItem) return null;

  const nav = [{ href: "#home", label: copy.home }, { href: "#menu", label: copy.menu }, { href: "#about", label: copy.about }, { href: "#contact", label: copy.contact }];
  return <div className={isAr ? "font-arabic" : ""}>
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur-xl">
      <div className="mx-auto grid h-18 max-w-7xl grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 px-4 sm:px-6 lg:px-8">
        <a href="#home" className="flex shrink-0 items-center gap-2" aria-label="ODA Burger home"><img src={restaurant.logo} alt="ODA Burger" className="h-13 w-13 rounded-sm object-cover" /><span className="hidden font-display text-xl font-black text-primary sm:block">ODA BURGER</span></a>
        <nav className="hidden items-center justify-center gap-7 lg:flex">{nav.map((n) => <a key={n.href} href={n.href} className="text-sm font-bold text-foreground/75 transition-colors hover:text-primary">{n.label}</a>)}</nav>
        <div className="flex items-center justify-end gap-1.5"><button onClick={() => setLocale(isAr ? "en" : "ar")} className="flex h-10 items-center rounded-md px-2 text-xs font-black text-primary transition-colors hover:bg-secondary" aria-label="Switch language"><span className={!isAr ? "text-primary" : "text-muted-foreground"}>EN</span><span className="mx-1 text-border">|</span><span className={isAr ? "text-primary" : "text-muted-foreground"}>AR</span></button><Button variant="icon" size="icon" onClick={() => setCartOpen(true)} aria-label={copy.basket} className="relative"><ShoppingBag size={19}/>{count > 0 && <span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-primary text-[10px] text-primary-foreground">{count}</span>}</Button><Button className="hidden sm:inline-flex" onClick={() => document.querySelector("#menu")?.scrollIntoView()}><ShoppingBag size={16}/>{copy.order}</Button><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(true)} aria-label={copy.nav}><Menu/></Button></div>
      </div>
    </header>

    {mobileOpen && <div className="fixed inset-0 z-50 bg-foreground/45 backdrop-blur-sm" onClick={() => setMobileOpen(false)}><nav className="absolute inset-y-0 end-0 flex w-[82%] max-w-sm flex-col bg-background p-6 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><img src={restaurant.logo} alt="ODA Burger" className="size-16 rounded-sm object-cover"/><Button variant="icon" size="icon" onClick={() => setMobileOpen(false)}><X/></Button></div><div className="mt-12 flex flex-col gap-2">{nav.map((n) => <a key={n.href} href={n.href} onClick={() => setMobileOpen(false)} className="border-b border-border py-4 font-display text-3xl font-black">{n.label}</a>)}</div><Button className="mt-auto" size="lg" onClick={() => { setMobileOpen(false); document.querySelector("#menu")?.scrollIntoView(); }}>{copy.order}</Button></nav></div>}

    <main>
      <section id="home" className="relative isolate min-h-[calc(100svh-4.5rem)] overflow-hidden bg-hero text-hero-foreground">
        <img src={heroItem.image} alt="ODA Burger 2JZ beef burger" className="absolute inset-0 h-full w-full object-cover object-[65%_48%] motion-safe:animate-[reveal_1s_ease-out]"/>
        <div className="absolute inset-0 bg-hero-overlay"/>
        <div className="relative mx-auto flex min-h-[calc(100svh-4.5rem)] max-w-7xl items-end px-4 pb-20 pt-24 sm:px-6 lg:px-8 lg:pb-24">
          <div className="max-w-3xl motion-safe:animate-[rise_.8s_ease-out]">
            <p className="mb-4 flex items-center gap-3 text-xs font-black uppercase tracking-[.2em] text-hero-muted"><span className="h-px w-8 bg-current"/>{copy.heroKicker}</p>
            <h1 className="font-display text-6xl font-black leading-[.85] sm:text-8xl lg:text-[8.5rem]">ODA<br/><span className="text-hero-accent">BURGER</span></h1>
            <p className="mt-6 font-display text-2xl font-bold sm:text-4xl">{isAr ? "كل قضمة، أسطورة." : restaurant.tagline}</p>
            <p className="mt-3 max-w-lg text-base text-hero-muted sm:text-lg">{copy.heroCopy}</p>
            <div className="mt-8 flex flex-wrap gap-3"><Button size="lg" onClick={() => document.querySelector("#menu")?.scrollIntoView()}>{copy.order}{isAr ? <ArrowLeft size={17}/> : <ArrowRight size={17}/>}</Button><Button variant="outline" size="lg" className="border-hero-muted/50 bg-transparent text-hero-foreground hover:bg-hero-foreground/10" onClick={() => document.querySelector("#menu")?.scrollIntoView()}>{copy.viewMenu}</Button></div>
          </div>
        </div>
        <div className="absolute bottom-0 end-0 hidden bg-primary px-8 py-5 text-primary-foreground lg:block"><span className="text-xs font-black uppercase tracking-[.2em]">أودا برقر · البحرين</span></div>
      </section>

      <SectionHeader eyebrow={copy.favorites} title={copy.favorites} copy={copy.favoritesCopy}/>
      <section className="mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{favoriteItems.map((item, index) => <ProductCard key={item.id} item={item} locale={locale} orderLabel={copy.quickOrder} currency={copy.currency} featured={index === 0} onOpen={() => openItem(item)} onOrder={() => addToCart(item)}/>)}</div></section>

      <section id="menu" className="bg-menu py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="eyebrow">{copy.fullMenu}</p><h2 className="section-title mt-3">{copy.fullMenu}</h2><p className="mt-3 max-w-xl text-muted-foreground">{copy.menuCopy}</p></div><div className="scrollbar-none flex gap-2 overflow-x-auto pb-2">{categories.map((cat) => <button key={cat} onClick={() => setCategory(cat)} className={`h-11 shrink-0 rounded-md border px-4 text-xs font-black transition-colors ${category === cat ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background text-foreground hover:border-primary/40"}`}>{cat === "all" ? copy.all : categoryLabels[cat][locale]}</button>)}</div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <ProductCard key={item.id} item={item} locale={locale} orderLabel={copy.quickOrder} currency={copy.currency} onOpen={() => openItem(item)} onOrder={() => addToCart(item)}/>)}</div></div></section>

      <section id="about" className="grid min-h-[700px] lg:grid-cols-2"><div className="relative min-h-[480px] overflow-hidden"><img src={aboutItem.image} alt="ODA Burger 1JZ meal" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute bottom-6 start-6 bg-primary px-5 py-4 text-primary-foreground"><span className="font-display text-2xl font-black">أودا برقر</span></div></div><div className="flex items-center bg-foreground px-6 py-20 text-background sm:px-12 lg:px-20"><div className="max-w-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-primary-light">{copy.story}</p><h2 className="mt-5 font-display text-5xl font-black leading-none sm:text-7xl">{copy.aboutTitle}</h2><p className="mt-8 text-lg leading-8 text-background/70">{copy.aboutCopy}</p><div className="mt-10 flex items-center gap-4 border-t border-background/15 pt-8"><span className="font-display text-4xl font-black text-primary-light">ODA</span><span className="text-sm text-background/55">{copy.footer}</span></div></div></div></section>

      <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Instagram</p><h2 className="section-title mt-3">{copy.social}</h2></div><a href={restaurant.instagram} target="_blank" rel="noreferrer" className="hidden text-sm font-black text-primary underline-offset-4 hover:underline sm:block">{restaurant.instagramHandle}</a></div><div className="mt-9 grid grid-cols-2 gap-3 md:grid-cols-4">{socialItems.map((item) => <a key={item.id} href={restaurant.instagram} target="_blank" rel="noreferrer" className="group relative aspect-[4/5] overflow-hidden rounded-md"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/><div className="absolute inset-0 grid place-items-center bg-foreground/0 transition-colors group-hover:bg-foreground/25"><Instagram className="scale-75 text-background opacity-0 transition-all group-hover:scale-100 group-hover:opacity-100"/></div></a>)}</div><div className="mt-7 text-center"><a href={restaurant.instagram} target="_blank" rel="noreferrer"><Button variant="outline"><Instagram size={17}/>{copy.follow}</Button></a></div></div></section>

      <section id="contact" className="bg-primary py-20 text-primary-foreground sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.2em] text-primary-foreground/65">{copy.find}</p><h2 className="mt-4 font-display text-5xl font-black sm:text-7xl">{copy.visit}</h2><p className="mt-5 max-w-lg text-primary-foreground/70">{copy.mapCopy}</p><div className="mt-8 flex flex-wrap gap-3"><a href={`tel:${restaurant.phone}`}><Button className="bg-primary-foreground text-primary hover:bg-primary-foreground/90"><Phone size={17}/>{copy.call}</Button></a><a href={`https://wa.me/${restaurant.whatsapp}`} target="_blank" rel="noreferrer"><Button className="bg-primary-foreground text-primary hover:bg-primary-foreground/90"><MessageCircle size={17}/>{copy.whatsapp}</Button></a><a href={restaurant.location} target="_blank" rel="noreferrer"><Button variant="outline" className="border-primary-foreground/40 bg-transparent text-primary-foreground hover:bg-primary-foreground/10"><MapPin size={17}/>{copy.directions}</Button></a></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-md bg-background p-6 text-foreground"><Phone className="text-primary"/><p className="mt-8 text-xs font-black uppercase text-muted-foreground">{copy.contact}</p><a className="mt-2 block font-display text-xl font-black" href={`tel:${restaurant.phone}`}>{restaurant.phoneDisplay}</a></div><div className="rounded-md bg-background p-6 text-foreground"><Clock3 className="text-primary"/><p className="mt-8 text-xs font-black uppercase text-muted-foreground">{copy.hours}</p><p className="mt-2 font-display text-xl font-black">{restaurant.openingHours ?? copy.hoursPending}</p></div></div></div></section>
    </main>

    <footer className="bg-footer py-12 text-footer-foreground"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-8 border-b border-footer-foreground/15 pb-10 md:grid-cols-[1fr_auto_auto]"><div className="flex items-center gap-4"><img src={restaurant.logo} alt="ODA Burger" className="size-20 rounded-sm object-cover"/><div><p className="font-display text-2xl font-black">ODA BURGER</p><p className="text-sm text-footer-foreground/55">{isAr ? "كل قضمة، أسطورة." : restaurant.tagline}</p></div></div><div className="flex flex-wrap gap-5 text-sm font-bold">{nav.map((n) => <a key={n.href} href={n.href} className="hover:text-primary-light">{n.label}</a>)}</div><a href={restaurant.instagram} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-sm font-bold hover:text-primary-light"><Instagram size={18}/>{restaurant.instagramHandle}</a></div><div className="pt-6 text-xs text-footer-foreground/45">© 2026 ODA BURGER · Bahrain</div></div></footer>

    <button onClick={() => setCartOpen(true)} className="fixed bottom-4 start-4 end-4 z-30 flex h-14 items-center justify-between rounded-md bg-primary px-5 font-bold text-primary-foreground shadow-xl sm:hidden" aria-label={copy.basket}><span className="flex items-center gap-2"><ShoppingBag size={19}/>{copy.order}</span><span>{count ? `${count} · ${total.toFixed(1)} ${copy.currency}` : copy.viewMenu}</span></button>

    {selected && <div className="fixed inset-0 z-[60] grid place-items-end bg-foreground/60 p-0 backdrop-blur-sm sm:place-items-center sm:p-5" onClick={() => setSelected(null)}><div role="dialog" aria-modal="true" aria-label={selected.name} className="max-h-[94svh] w-full overflow-auto rounded-t-md bg-background shadow-2xl sm:max-w-3xl sm:rounded-md" onClick={(e) => e.stopPropagation()}><div className="grid md:grid-cols-2"><div className="relative min-h-72"><img src={selected.image} alt={selected.name} className="absolute inset-0 h-full w-full object-cover"/><button onClick={() => setSelected(null)} className="absolute start-4 top-4 grid size-10 place-items-center rounded-full bg-background text-foreground shadow"><X size={19}/></button></div><div className="p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">{categoryLabels[selected.category][locale]}</p><h3 className="mt-2 font-display text-4xl font-black">{isAr ? selected.nameAr : selected.name}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{isAr ? selected.descriptionAr : selected.description}</p>{selected.sandwich && <div className="mt-7 grid grid-cols-2 gap-2">{(["sandwich", "meal"] as const).map((choice) => <button key={choice} onClick={() => setOption(choice)} className={`rounded-md border p-4 text-start transition-colors ${option === choice ? "border-primary bg-secondary" : "border-border"}`}><span className="block text-xs font-bold text-muted-foreground">{copy[choice]}</span><span className="mt-1 block font-display text-xl font-black">{selected[choice]?.toFixed(1)} {copy.currency}</span>{option === choice && <Check size={16} className="mt-2 text-primary"/>}</button>)}</div>} {!selected.sandwich && <p className="mt-7 font-display text-3xl font-black text-primary">{selectedPrice.toFixed(1)} {copy.currency}</p>}<Button size="lg" className="mt-7 w-full" onClick={() => addToCart(selected, option)}><Plus size={18}/>{copy.add}<span className="ms-auto">{selectedPrice.toFixed(1)} {copy.currency}</span></Button></div></div></div></div>}

    {cartOpen && <div className="fixed inset-0 z-[70] bg-foreground/55 backdrop-blur-sm" onClick={() => setCartOpen(false)}><aside role="dialog" aria-modal="true" aria-label={copy.cart} className="absolute inset-y-0 end-0 flex w-full max-w-md flex-col bg-background shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between border-b border-border p-5"><div><p className="text-xs font-black uppercase tracking-[.18em] text-primary">ODA BURGER</p><h2 className="font-display text-3xl font-black">{copy.cart}</h2></div><Button variant="icon" size="icon" onClick={() => setCartOpen(false)}><X/></Button></div><div className="flex-1 overflow-y-auto p-5">{!cart.length ? <div className="grid h-full place-items-center text-center"><div><ShoppingBag className="mx-auto text-primary" size={42}/><p className="mt-4 max-w-xs font-display text-2xl font-black">{copy.empty}</p><Button className="mt-6" onClick={() => { setCartOpen(false); document.querySelector("#menu")?.scrollIntoView(); }}>{copy.viewMenu}</Button></div></div> : <div className="space-y-3">{cart.map((line, i) => <div key={`${line.item.id}-${line.option}`} className="grid grid-cols-[72px_minmax(0,1fr)_auto] gap-3 border-b border-border pb-4"><img src={line.item.image} alt="" className="size-18 rounded-sm object-cover"/><div className="min-w-0"><h3 className="truncate font-display text-lg font-black">{isAr ? line.item.nameAr : line.item.name}</h3>{line.option !== "single" && <p className="text-xs text-muted-foreground">{line.option === "meal" ? copy.meal : copy.sandwich}</p>}<p className="mt-1 text-sm font-bold text-primary">{line.price.toFixed(1)} {copy.currency}</p><div className="mt-2 flex items-center gap-2"><button className="grid size-7 place-items-center rounded-sm bg-secondary" onClick={() => updateQty(i,-1)} aria-label="Decrease"><Minus size={13}/></button><span className="w-5 text-center text-sm font-black">{line.quantity}</span><button className="grid size-7 place-items-center rounded-sm bg-secondary" onClick={() => updateQty(i,1)} aria-label="Increase"><Plus size={13}/></button></div></div><button onClick={() => setCart((current) => current.filter((_, ix) => ix !== i))} className="text-muted-foreground hover:text-primary" aria-label={copy.remove}><Trash2 size={17}/></button></div>)}</div>}</div>{cart.length > 0 && <div className="border-t border-border bg-secondary/50 p-5"><div className="mb-4 flex items-center justify-between font-display text-xl font-black"><span>{copy.subtotal}</span><span>{total.toFixed(1)} {copy.currency}</span></div><a href={whatsappUrl} target="_blank" rel="noreferrer" className="block"><Button size="lg" className="w-full"><MessageCircle size={18}/>{copy.checkout}</Button></a></div>}</aside></div>}
  </div>;
}

function SectionHeader({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="mx-auto max-w-7xl px-4 pb-9 pt-20 sm:px-6 sm:pt-28 lg:px-8"><p className="eyebrow">{eyebrow}</p><div className="mt-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><h2 className="section-title">{title}</h2><p className="max-w-md text-sm text-muted-foreground sm:text-end">{copy}</p></div></div>; }
function ProductCard({ item, locale, orderLabel, currency, featured, onOpen, onOrder }: { item: MenuItem; locale: Locale; orderLabel: string; currency: string; featured?: boolean; onOpen: () => void; onOrder: () => void }) { const isAr = locale === "ar"; const price = item.sandwich ?? item.price ?? 0; return <article className={`group overflow-hidden rounded-md border border-border bg-card transition-all duration-300 hover:-translate-y-1 hover:shadow-card ${featured ? "sm:col-span-2 lg:col-span-1" : ""}`}><button onClick={onOpen} className="block w-full text-start"><div className="aspect-[4/3] overflow-hidden bg-secondary"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-2xl font-black">{isAr ? item.nameAr : item.name}</h3><p className="mt-1 line-clamp-2 min-h-10 text-sm leading-5 text-muted-foreground">{isAr ? item.descriptionAr : item.description}</p></div><ChevronRight className={`mt-1 shrink-0 text-primary transition-transform group-hover:translate-x-1 ${isAr ? "rotate-180" : ""}`} size={18}/></div></div></button><div className="flex items-center justify-between border-t border-border px-5 py-4"><span className="font-display text-lg font-black text-primary">{item.sandwich ? `${isAr ? "من" : "From"} ` : ""}{price.toFixed(1)} {currency}</span><Button size="sm" onClick={onOrder}><Plus size={15}/>{orderLabel}</Button></div></article>; }
